import { NextResponse } from 'next/server';
import dbConnect from '@/utils/mongodb';
import Freelancer from '@/models/Freelancer';

const MOCK_FREELANCERS = [
  {
    name: 'Sarah Chen',
    title: 'Senior Full-Stack Developer',
    bio: 'Passionate full-stack developer with 8+ years of experience in React, Node.js, and cloud architectures.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=sarah',
    skills: ['React', 'Next.js', 'Node.js', 'TypeScript', 'MongoDB', 'AWS', 'GraphQL'],
    rating: 4.9,
    completedJobs: 47,
    hourlyRate: 95,
    availability: 'available',
    location: 'San Francisco, USA',
    portfolio: ['https://github.com/sarahchen'],
    responseTime: '< 1 hour',
    successRate: 98,
  },
  {
    name: 'Marcus Rodriguez',
    title: 'Blockchain & Web3 Engineer',
    bio: 'Solidity expert building DeFi protocols and NFT platforms. Audit-ready smart contracts.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=marcus',
    skills: ['Solidity', 'React', 'TypeScript', 'Node.js', 'REST API', 'MongoDB'],
    rating: 4.8,
    completedJobs: 32,
    hourlyRate: 120,
    availability: 'available',
    location: 'Berlin, Germany',
    portfolio: ['https://github.com/marcusr'],
    responseTime: '< 2 hours',
    successRate: 97,
  },
  {
    name: 'Priya Sharma',
    title: 'React & UI/UX Specialist',
    bio: 'Creating beautiful, accessible, and performant user interfaces. Design systems evangelist.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=priya',
    skills: ['React', 'Next.js', 'TailwindCSS', 'UI/UX Design', 'TypeScript', 'Testing'],
    rating: 4.9,
    completedJobs: 63,
    hourlyRate: 85,
    availability: 'available',
    location: 'Mumbai, India',
    portfolio: ['https://priyaui.design'],
    responseTime: '< 30 mins',
    successRate: 99,
  },
  {
    name: 'Alex Petrov',
    title: 'DevOps & Cloud Architect',
    bio: 'Kubernetes, Terraform, and AWS specialist. Building scalable infrastructure for startups.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=alex',
    skills: ['AWS', 'Docker', 'DevOps', 'Node.js', 'Python', 'PostgreSQL'],
    rating: 4.7,
    completedJobs: 28,
    hourlyRate: 110,
    availability: 'busy',
    location: 'Toronto, Canada',
    portfolio: ['https://github.com/apetrov'],
    responseTime: '< 3 hours',
    successRate: 96,
  },
  {
    name: 'Emma Tanaka',
    title: 'AI/ML Engineer',
    bio: 'Deep learning researcher turned product engineer. NLP, computer vision, and recommendation systems.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=emma',
    skills: ['Python', 'Machine Learning', 'React', 'Node.js', 'PostgreSQL', 'REST API'],
    rating: 4.8,
    completedJobs: 19,
    hourlyRate: 130,
    availability: 'available',
    location: 'Tokyo, Japan',
    portfolio: ['https://github.com/emmat'],
    responseTime: '< 1 hour',
    successRate: 100,
  },
  {
    name: 'James Wright',
    title: 'Mobile Developer',
    bio: 'Cross-platform mobile developer specializing in React Native and Flutter apps.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=james',
    skills: ['Mobile Development', 'React', 'TypeScript', 'Node.js', 'REST API', 'Testing'],
    rating: 4.6,
    completedJobs: 35,
    hourlyRate: 90,
    availability: 'available',
    location: 'London, UK',
    portfolio: ['https://github.com/jwright'],
    responseTime: '< 2 hours',
    successRate: 94,
  },
  {
    name: 'Fatima Al-Rashid',
    title: 'Backend & Database Engineer',
    bio: 'Backend expert focused on scalable microservices and database optimization.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=fatima',
    skills: ['Node.js', 'Python', 'MongoDB', 'PostgreSQL', 'GraphQL', 'Docker', 'REST API'],
    rating: 4.9,
    completedJobs: 41,
    hourlyRate: 100,
    availability: 'available',
    location: 'Dubai, UAE',
    portfolio: ['https://github.com/fatimadev'],
    responseTime: '< 1 hour',
    successRate: 98,
  },
  {
    name: 'Lucas Moretti',
    title: 'Full-Stack Web3 Developer',
    bio: 'Building decentralized applications. Wagmi, Viem, and Ethers.js specialist.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lucas',
    skills: ['Solidity', 'React', 'Next.js', 'TypeScript', 'Node.js', 'TailwindCSS'],
    rating: 4.7,
    completedJobs: 22,
    hourlyRate: 115,
    availability: 'available',
    location: 'Milan, Italy',
    portfolio: ['https://github.com/lucasweb3'],
    responseTime: '< 2 hours',
    successRate: 95,
  },
  {
    name: 'Aisha Okonkwo',
    title: 'Data Engineer & Analyst',
    bio: 'Data pipeline architect with expertise in real-time analytics and visualization.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=aisha',
    skills: ['Python', 'PostgreSQL', 'AWS', 'Docker', 'REST API', 'Machine Learning'],
    rating: 4.8,
    completedJobs: 29,
    hourlyRate: 105,
    availability: 'busy',
    location: 'Lagos, Nigeria',
    portfolio: ['https://github.com/aishadata'],
    responseTime: '< 3 hours',
    successRate: 97,
  },
  {
    name: 'Daniel Kim',
    title: 'React Native & iOS Developer',
    bio: 'Building polished mobile experiences. App Store featured twice.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=daniel',
    skills: ['Mobile Development', 'React', 'TypeScript', 'Node.js', 'UI/UX Design'],
    rating: 4.9,
    completedJobs: 38,
    hourlyRate: 100,
    availability: 'available',
    location: 'Seoul, South Korea',
    portfolio: ['https://github.com/danielkim'],
    responseTime: '< 1 hour',
    successRate: 99,
  },
  {
    name: 'Clara Dubois',
    title: 'Vue.js & Nuxt Developer',
    bio: 'Frontend specialist with a passion for clean code and smooth animations.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=clara',
    skills: ['Vue.js', 'JavaScript', 'TailwindCSS', 'Node.js', 'REST API', 'Testing'],
    rating: 4.6,
    completedJobs: 44,
    hourlyRate: 80,
    availability: 'available',
    location: 'Paris, France',
    portfolio: ['https://github.com/clarad'],
    responseTime: '< 1 hour',
    successRate: 96,
  },
  {
    name: 'Omar Hassan',
    title: 'Security & Smart Contract Auditor',
    bio: 'Certified blockchain security auditor. Securing DeFi protocols and dApps.',
    avatar: 'https://api.dicebear.com/9.x/avataaars/svg?seed=omar',
    skills: ['Solidity', 'Python', 'DevOps', 'Testing', 'Node.js'],
    rating: 4.9,
    completedJobs: 16,
    hourlyRate: 150,
    availability: 'available',
    location: 'Cairo, Egypt',
    portfolio: ['https://github.com/omaraudit'],
    responseTime: '< 4 hours',
    successRate: 100,
  },
];

export async function POST() {
  try {
    await dbConnect();
    
    // Clear existing freelancers
    await Freelancer.deleteMany({});
    
    // Insert mock freelancers
    const inserted = await Freelancer.insertMany(MOCK_FREELANCERS);

    return NextResponse.json({
      success: true,
      message: `Seeded ${inserted.length} freelancers successfully.`,
      count: inserted.length,
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 });
  }
}
